version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx700m -Xms700m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - 9200:9200
    networks:
      - net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - net

networks:
  net:
    driver: bridge
    